### ISSUE TITLE
Invalid assignment expression.

### ISSUE THREAD

**Issue by Jerax1981** [leobouard/PasswordReminderByEmail#1]
Hello Leo,

when I try lo lunch the script, i get immediatly an error:

 .\script.ps1 -ExpireInDays 1..90 -TestRecipient 'Name@Domain.it' In C:\TEMP\PasswordReminder\script.ps1:5 car:35
+     [System.IO.FileInfo]$Layout = "$PSScriptRoot\layout.html",
Invalid assignment expression. The input to an assignment operator must be an object capable of
accept assignments, such as a variable or property.
    + CategoryInfo : ParserError : (:) [], ParseException
    + FullyQualifiedErrorId : InvalidLeftHandSide.

could you please help me?

**Comment by leobouard** [comment]
Hi Jerax1981!

Thank you for taking the time to open an issue, it is appreciated! 😊
I didn't get this error message in my prod environment, but I managed to replicate the issue on my computer.

The new version of the file `script.ps1` should correct the issue. If you have already customized the script, you can simply update the line 5 (in the parameter declaration).

### Before

```powershell
[System.IO.FileInfo]$Layout = "$PSScriptRoot\layout.html",
```

### Now

```powershell
[string]$Layout = ((Get-Item -Path "$PSScriptRoot\layout.html").FullName),
```

**Comment by Jerax1981** [comment]
Thanks for the answer!!!

I get a lot of new errors now...

```
InvalidOperation: C:\Temp\PasswordReminder\script.ps1:5
Line |
   5 |  … ng]$Layout = ((Get-Item -Path "$PSScriptRoot\layout.html").FullName),
     |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | 'FullName' is a ReadOnly property.
Transcript started, output file is C:\Temp\PasswordReminder\logs\PasswordReminderByEmail__2024-01-30_114747.txt
VERBOSE: Performing the operation "Remove File" on target "C:\Temp\PasswordReminder\logs\PasswordReminderByEmail__2024-01-30_114425.txt".
VERBOSE: Performing the operation "Remove File" on target "C:\Temp\PasswordReminder\logs\PasswordReminderByEmail__2024-01-30_114747.txt".
Remove-Item: C:\Temp\PasswordReminder\script.ps1:19
Line |
  19 |  } | Remove-Item -Force -Confirm:$false -Verbose
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The process cannot access the file 'C:\Temp\PasswordReminder\logs\PasswordReminderByEmail__2024-01-30_114747.txt' because it is being used by another process.
Get-ADUser: C:\Temp\PasswordReminder\script.ps1:31
Line |
  31 |  … (PasswordExpired -eq $false)} -Properties * -SearchBase $SearchBase |
     |                                                            ~~~~~~~~~~~
     | Cannot validate argument on parameter 'SearchBase'. The argument is null. Provide a valid value for the argument, and then try running the command again.
New-TimeSpan: C:\Temp\PasswordReminder\script.ps1:38
Line |
  38 |      $passwordAge = (New-TimeSpan -Start $_.PasswordLastSet -End (Get- …
     |                                          ~~~~~~~~~~~~~~~~~~
     | Cannot bind parameter 'Start' to the target. Exception setting "Start": "Cannot convert null to type "System.DateTime"."
Add-Member: C:\Temp\PasswordReminder\script.ps1:40
Line |
  40 |      $_ | Add-Member -MemberType "NoteProperty" -Name "PasswordAge" -V …
     |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot bind argument to parameter 'InputObject' because it is null.
Add-Member: C:\Temp\PasswordReminder\script.ps1:41
Line |
  41 |      $_ | Add-Member -MemberType "NoteProperty" -Name "MaxPasswordAge" …
     |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot bind argument to parameter 'InputObject' because it is null.
Add-Member: C:\Temp\PasswordReminder\script.ps1:42
Line |
  42 |      $_ | Add-Member -MemberType "NoteProperty" -Name "PasswordPolicy" …
     |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot bind argument to parameter 'InputObject' because it is null.
Add-Member: C:\Temp\PasswordReminder\script.ps1:43
Line |
  43 |      $_ | Add-Member -MemberType "NoteProperty" -Name "Template" -Valu …
     |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot bind argument to parameter 'InputObject' because it is null.
Transcript stopped, output file is C:\Temp\PasswordReminder\logs\PasswordReminderByEmail__2024-01-30_114747.txt
```


For your information:

I'm lunching the script as Domanin administrator in a DC using PowerShell 7.4.1

I have edited scripts.ps1 only in the sender email address (From) and SMTP server (SmtpServer).
I Created a new template and edited the json file.
In the Html instead I just add our logo.

**Comment by FraFau** [comment]
> Thanks for the answer!!!
> 
> I get a lot of new errors now...
> 
> ```
> InvalidOperation: C:\Temp\PasswordReminder\script.ps1:5
> Line |
>    5 |  … ng]$Layout = ((Get-Item -Path "$PSScriptRoot\layout.html").FullName),
>      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      | 'FullName' is a ReadOnly property.
> Transcript started, output file is C:\Temp\PasswordReminder\logs\PasswordReminderByEmail__2024-01-30_114747.txt
> VERBOSE: Performing the operation "Remove File" on target "C:\Temp\PasswordReminder\logs\PasswordReminderByEmail__2024-01-30_114425.txt".
> VERBOSE: Performing the operation "Remove File" on target "C:\Temp\PasswordReminder\logs\PasswordReminderByEmail__2024-01-30_114747.txt".
> Remove-Item: C:\Temp\PasswordReminder\script.ps1:19
> Line |
>   19 |  } | Remove-Item -Force -Confirm:$false -Verbose
>      |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      | The process cannot access the file 'C:\Temp\PasswordReminder\logs\PasswordReminderByEmail__2024-01-30_114747.txt' because it is being used by another process.
> Get-ADUser: C:\Temp\PasswordReminder\script.ps1:31
> Line |
>   31 |  … (PasswordExpired -eq $false)} -Properties * -SearchBase $SearchBase |
>      |                                                            ~~~~~~~~~~~
>      | Cannot validate argument on parameter 'SearchBase'. The argument is null. Provide a valid value for the argument, and then try running the command again.
> New-TimeSpan: C:\Temp\PasswordReminder\script.ps1:38
> Line |
>   38 |      $passwordAge = (New-TimeSpan -Start $_.PasswordLastSet -End (Get- …
>      |                                          ~~~~~~~~~~~~~~~~~~
>      | Cannot bind parameter 'Start' to the target. Exception setting "Start": "Cannot convert null to type "System.DateTime"."
> Add-Member: C:\Temp\PasswordReminder\script.ps1:40
> Line |
>   40 |      $_ | Add-Member -MemberType "NoteProperty" -Name "PasswordAge" -V …
>      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      | Cannot bind argument to parameter 'InputObject' because it is null.
> Add-Member: C:\Temp\PasswordReminder\script.ps1:41
> Line |
>   41 |      $_ | Add-Member -MemberType "NoteProperty" -Name "MaxPasswordAge" …
>      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      | Cannot bind argument to parameter 'InputObject' because it is null.
> Add-Member: C:\Temp\PasswordReminder\script.ps1:42
> Line |
>   42 |      $_ | Add-Member -MemberType "NoteProperty" -Name "PasswordPolicy" …
>      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      | Cannot bind argument to parameter 'InputObject' because it is null.
> Add-Member: C:\Temp\PasswordReminder\script.ps1:43
> Line |
>   43 |      $_ | Add-Member -MemberType "NoteProperty" -Name "Template" -Valu …
>      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      | Cannot bind argument to parameter 'InputObject' because it is null.
> Transcript stopped, output file is C:\Temp\PasswordReminder\logs\PasswordReminderByEmail__2024-01-30_114747.txt
> ```
> 
> For your information:
> 
> I'm lunching the script as Domanin administrator in a DC using PowerShell 7.4.1
> 
> I have edited scripts.ps1 only in the sender email address (From) and SMTP server (SmtpServer). I Created a new template and edited the json file. In the Html instead I just add our logo.

exactly the same here (with both of the line 5 versions)

**Comment by leobouard** [comment]
There is still some quirks that I'm not used to in PowerShell 7, but all your issues seems related to the fact the default value for the parameter "Layout" is in ReadOnly.

Here's the new code for Line 5:

### Now

```powershell
[string]$Layout = ((Get-Item -Path "$PSScriptRoot\layout.html" | Select-Object @{N='Path';E={$_.FullName}}).Path),
```

It's not the cleanest code I've ever written, it's the best solution I've come up with so far.

**Comment by FraFau** [comment]
Answer found,

If you DL the zip file of the code, you'll get a strange caracter at the beginning of the first line (you can see it with Notepad++) :
![image](https://github.com/leobouard/PasswordReminderByEmail/assets/59955425/78f19280-ed9c-456e-89c2-cdb7a3eb50e5)

Just remove the ZWNBSP from the BOM signature and the script will work fine !

**Comment by Jerax1981** [comment]
> Answer found,
> 
> If you DL the zip file of the code, you'll get a strange caracter at the beginning of the first line (you can see it with Notepad++) : ![image](https://private-user-images.githubusercontent.com/59955425/301145765-78f19280-ed9c-456e-89c2-cdb7a3eb50e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NzY3MTcsIm5iZiI6MTcwNjc3NjQxNywicGF0aCI6Ii81OTk1NTQyNS8zMDExNDU3NjUtNzhmMTkyODAtZWQ5Yy00NTZlLTg5YzItY2RiN2EzZWI1MGU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDA4MzMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhNzRkNmY0ZGNhNWU1ZjQzNzAwMTg2ZjA5YWZmNTgyNmNmOWY2ODYxN2UwNmFiNmVjZjRkYWE3MmI5ODRlYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TPrRRU8N9ja3hDQ2UsaQ2LfRKmwCpT1vhncPmtHpXUY)
> 
> Just remove the ZWNBSP from the BOM signature and the script will work fine !

I re-download the Zip and i don't have the strange caracter at beginning (opened with notepad++ and notepad classic)

> There is still some quirks that I'm not used to in PowerShell 7, but all your issues seems related to the fact the default value for the parameter "Layout" is in ReadOnly.
> 
> Here's the new code for Line 5:
> 
> ### Now
> ```powershell
> [string]$Layout = ((Get-Item -Path "$PSScriptRoot\layout.html" | Select-Object @{N='Path';E={$_.FullName}}).Path),
> ```
> 
> It's not the cleanest code I've ever written, it's the best solution I've come up with so far.

I tried with [string]$Layout = ((Get-Item -Path "$PSScriptRoot\layout.html" | Select-Object @{N='Path';E={$_.FullName}}).Path),

but the problem is still present:

SetValueInvocationException: C:\Temp\PasswordReminder\PasswordReminderByEmail.ps1:5
Line |
   5 |  … g]$Layout = ((Get-Item -Path "$PSScriptRoot\layout.html" | Select-Obj …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception setting "DistinguishedName": "The adapter cannot set the value of property "DistinguishedName"."

Get-ADUser: C:\Temp\PasswordReminder\PasswordReminderByEmail.ps1:37
Line |
  37 |  … -ADUser -LDAPFilter $ldapFilter -Properties * -SearchBase $SearchBase
     |                                                              ~~~~~~~~~~~
     | Cannot validate argument on parameter 'SearchBase'. The argument is null. Provide a valid value for the argument, and then try running the command again.
New-TimeSpan: C:\Temp\PasswordReminder\PasswordReminderByEmail.ps1:43
Line |
  43 |      $passwordAge = (New-TimeSpan -Start $_.PasswordLastSet -End (Get- …
     |                                          ~~~~~~~~~~~~~~~~~~
     | Cannot bind parameter 'Start' to the target. Exception setting "Start": "Cannot convert null to type "System.DateTime"."
Add-Member: C:\Temp\PasswordReminder\PasswordReminderByEmail.ps1:45
Line |
  45 |      $_ | Add-Member -MemberType "NoteProperty" -Name "PasswordAge" -V …
     |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot bind argument to parameter 'InputObject' because it is null.
Add-Member: C:\Temp\PasswordReminder\PasswordReminderByEmail.ps1:46
Line |
  46 |      $_ | Add-Member -MemberType "NoteProperty" -Name "MaxPasswordAge" …
     |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot bind argument to parameter 'InputObject' because it is null.
Add-Member: C:\Temp\PasswordReminder\PasswordReminderByEmail.ps1:47
Line |
  47 |      $_ | Add-Member -MemberType "NoteProperty" -Name "PasswordPolicy" …
     |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot bind argument to parameter 'InputObject' because it is null.
Add-Member: C:\Temp\PasswordReminder\PasswordReminderByEmail.ps1:48
Line |
  48 |      $_ | Add-Member -MemberType "NoteProperty" -Name "Template" -Valu …
     |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot bind argument to parameter 'InputObject' because it is null.
Transcript stopped, output file is C:\Temp\PasswordReminder\logs\PasswordReminderByEmail__2024-02-01_094058.txt

**Comment by tech62** [comment]
Hi same error for me :/

**Comment by leobouard** [comment]
Hi everyone!

[FraFau](https://github.com/FraFau) was correct: it seems like the problem comes from the UTF8**bom** encoding.
You can try saving your file using UTF8 encoding (using Notepad++ or VSCode for example) and see if that works better.

If the parameter autocompletion do work, then the issue should be solved!

**Comment by Jerax1981** [comment]
> Hi everyone!
> 
> [FraFau](https://github.com/FraFau) was correct: it seems like the problem comes from the UTF8**bom** encoding. You can try saving your file using UTF8 encoding (using Notepad++ or VSCode for example) and see if that works better.
> 
> If the parameter autocompletion do work, then the issue should be solved!

Thank! you are right! the scripts now works but i have several question for you:

By configuring the email sending as it is written in your scripts the account that sends the emails is obviously not authenticated on the microsoft tenant so the script fails me with the following message: 

The SMTP server requires a secure connection or the client was not authenticated. The server response was: 5.7.57 Client not authenticated to send mail. [MI0P293CA0014.ITAP293.PROD.OUTLOOK.COM
     | 2024-02-07T14:42:22.318Z 08DC26C730FD35E0]

how do you solve this problem? 

Do you create the scheduled task using the sending user as the authorized user to send the emails? But by doing so that user does not access to fine-grained password policies for obvious security reasons on the DC.

I'm a little confused.

**Comment by Jerax1981** [comment]
Ok! i solved... I used our internal SMTP and it worked without authentication! many thanks for your support!

Your script is amazing!
